name: Update docker compose file on production

on:
  push:
    branches:
      - production
    paths:
      - 'docker-compose.yml'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Copy docker compose file
        run: |
          mkdir -p /spotify/runner/.ssh
          touch /spotify/runner/.ssh/id_rsa
          echo "${{ secrets.PRODUCTION_SSH }}" > /spotify/runner/.ssh/id_rsa
          chmod 600 /spotify/runner/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.PRODUCTION_HOST }} >> ~/.ssh/known_hosts
          ssh ${{ secrets.PRODUCTION_USERNAME }}@${{ secrets.PRODUCTION_HOST }} "mkdir -p ~/spotify"
          scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.PRODUCTION_USERNAME }}@${{ secrets.PRODUCTION_HOST }}:~/spotify/docker-compose.yml
          ssh ${{ secrets.PRODUCTION_USERNAME }}@${{ secrets.PRODUCTION_HOST }} "cd ~/spotify && docker compose down"
          ssh ${{ secrets.PRODUCTION_USERNAME }}@${{ secrets.PRODUCTION_HOST }} "cd ~/spotify && docker network create traefik-net || true"
          ssh ${{ secrets.PRODUCTION_USERNAME }}@${{ secrets.PRODUCTION_HOST }} "cd ~/spotify && docker compose up -d"
